name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
    
    - name: Build with Maven
      run: mvn clean install
    
    - name: Run Tests
      run: mvn test
      env:
        CHROME_HEADLESS: true
        DISPLAY: :99
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/cucumber-reports/ 
